### ISSUE TITLE
createFile() cuts text files at first line starting with "----"

### ISSUE THREAD

**Issue by ferenc-hechler** [pCloud/pcloud-sdk-java#31] opened 2022-02-02 16:46 UTC
I use the following code to upload a local file to pCloud:

```
    apiClient = ...
    File file = new File("test.txt");

    System.out.println("FILESIZE: " + localFile.length());
    RemoteFile uploadedFile = apiClient.createFile(
        RemoteFolder.ROOT_FOLDER_ID,
        localFile.getName(),
        DataSource.create(localFile))
            .execute();
    System.out.println("UPLOADED: " + uploadedFile.size());
```

This code works fine, as long as the text file does not contain a line starting with '----'.
For example the following text:

```
Transmission Control Protocol
Functional Specification

Currently defined options include (kind indicated in octal):

Kind     Length    Meaning
----     ------    -------
 0         -       End of option list.
 1         -       No-Operation.
 2         4       Maximum Segment Size.

Specific Option Definitions

End of Option List
```

Uploading this file gives the following output:

```
FILESIZE: 348
UPLOADED: 149
```

and looking at the uploaded text it stops before the first line starting with  "----":

```
Transmission Control Protocol
Functional Specification

Currently defined options include (kind indicated in octal):

Kind     Length    Meaning
```

So lines starting with four "-" signs are somehow misinterpreted as End-Of-Text.

**Comment by georgi-neykov-hub** [comment] 2022-02-03 10:36
@ferenc-hechler the behavior is caused by the multipart body boundary (`---`) being currently used. This will be fixed altogether with #30 with the next release, I will keep you updated.

**Comment by georgi-neykov-hub** [comment] 2022-02-08 08:22
@ferenc-hechler, the issue is fixed with version 1.7.0 of the SDK. I will keep open the issue for some time for feedback.

**Comment by ferenc-hechler** [comment] 2022-02-08 21:04
Version 1.7.0 is not yet published in maven central, so I checked out the tag "1.7.0".
Unfortunately file upload does not work.
Perhaps I made a mistake in referencing the checked out source version 1.7.0, but here is what I get:

```
java.lang.IllegalArgumentException: Parameter is not formatted correctly: "@version@-e10064b5-318a-4374-8ba4-35e04e6ce8af----" for: "multipart/form-data; boundary=----pCloud-SDK-@version@-e10064b5-318a-4374-8ba4-35e04e6ce8af----"
	at okhttp3.MediaType$Companion.get(MediaType.kt:120)
	at okhttp3.MultipartBody.<init>(MultipartBody.kt:38)
	at okhttp3.MultipartBody$Builder.build(MultipartBody.kt:273)
	at com.pcloud.sdk.internal.RealApiClient.createFile(RealApiClient.java:309)
	at com.pcloud.sdk.internal.RealApiClient.createFile(RealApiClient.java:236)
	at com.pcloud.sdk.internal.RealApiClient.createFile(RealApiClient.java:221)
	at de.hechler.pgpencrypter.pcloud.PCloudUploaderTest.uploadGetsCutTest(PCloudUploaderTest.java:29)
```

I will retry, if the maven build is available.

My testcase is using a file DataSource:

```
RemoteFile uploadedFile = apiClient.createFile(
	RemoteFolder.ROOT_FOLDER_ID,
	localFile.getName(),
	DataSource.create(localFile))
		.execute();
```

**Comment by ferenc-hechler** [comment] 2022-02-08 21:18
just recognized, that the exception is thrown in createFile() and not in execute(). Tried to call another api method "loadFolder(0)" to verify, that auth works and root folder could be loaded successfully without any exceptions.

**Comment by ferenc-hechler** [comment] 2022-02-08 21:31
Sorry for the noise, found the issue:

in "/pcloud-sdk-java-170/java-core/src/main/java-templates/com/pcloud/sdk/internal/Version.java" I had to replace "@version@" with "1.7.0":

```
public final class Version {
//    public static final String NAME = "@version@";
    public static final String NAME = "1.7.0";
    private Version(){ }
}
```

Now everything works fine, and the file is transfered without cutting after lines starting with "----"   🥇

**Closed** 2022-02-09 13:06 UTC
